volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    command: >
      sh -c "python manage.py migrate &&
             gunicorn foodgram_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_foodgram:/app/staticfiles
      - media_foodgram:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - static_foodgram:/app/result_build/build/
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static_foodgram:/staticfiles
      - media_foodgram:/media
    depends_on:
      - backend
